# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram-Clone(Firebase)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram-Clone(Firebase)

pod 'Appirater'
pod 'SDWebImage' 
#Firebase
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Storage'

end
