# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMDemo' do

 pod 'Alamofire'
 pod 'SwiftyJSON'
 pod 'SDWebImage', :modular_headers => true
end
